analyzer:
  errors:
    inference_failure_on_instance_creation: ignore
    lines_longer_than_80_chars: ignore
    strict_raw_type: ignore
include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false
