name: zamaan
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dotted_line: ^3.2.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  font_awesome_flutter: ^10.7.0
  ftoast: ^2.0.0
  get_it: ^8.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  iconly: ^1.0.1
  internet_connection_checker_plus: ^2.5.2
  intl: ^0.19.0
  local_auth: ^2.3.0
  lottie: ^3.1.3
  meta: ^1.15.0
  path_provider: ^2.1.4
  persian_datetime_picker: ^3.1.0
  provider: ^6.1.2
  shamsi_date: ^1.0.4
  smooth_page_indicator: ^1.2.0+3
  stack_trace: ^1.11.1
  supabase_flutter: ^2.8.0
  uuid: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^10.0.0
  build_runner: ^2.4.11
  hive_generator: ^2.0.1
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/
