name: zamaan
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  bloc: ^8.1.4
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dotted_line: ^3.2.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  font_awesome_flutter: ^10.7.0
  ftoast: ^2.0.0
  get_it: ^8.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  iconly: ^1.0.1
  intl: ^0.19.0
  path_provider: ^2.1.4
  persian_datetime_picker: ^2.7.0
  provider: ^6.1.2
  shamsi_date: ^1.0.4
  smooth_page_indicator: ^1.2.0+3
  uuid: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  hive_generator: ^2.0.1
  mocktail: ^1.0.4
  bloc_test: ^9.1.7
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
